---

- include_vars: "{{ ansible_os_family }}.yml"

- include: pre_install.yml

- include: pip_install.yml
  when: shinken_install == 'pip'

- include: git_install.yml
  when: shinken_install == 'git'

- include: post_install.yml
