---

- name: Install pip dependencies
  apt:
    name: "{{ item }}"
  with_items:
    - python-pip

- name: Install Shinken from pip
  pip:
    name: shinken
    version: "{{ shinken_version | default('2.4') }}"
