---

- name: Install Shinken WebUI and auth modules.
  command: "/usr/bin/shinken install {{ item }}"
  when: "'{{ item }}' not in shinken_inventory.stdout_lines"
  with_items:
    - webui
    - auth-cfg-password
    - sqlitedb

- name: Fix 'wall' page
  # https://github.com/shinken-monitoring/mod-webui/issues/102#issuecomment-77958430
  replace:
    dest: /var/lib/shinken/modules/webui/plugins/wall/wall.py
    regexp: from helper import hst_srv_sort
    replace: from shinken.misc.sorter import hst_srv_sort
  notify: restart shinken

- name: Deploy webui and sqlite configuration
  template:
    dest: "/etc/shinken/modules/{{ item }}.cfg"
    src: "../templates/{{ item }}.cfg.j2"
  notify: restart shinken
  with_items:
    - webui
    - sqlitedb
