---

- name: Install Shinken WebUI and auth modules.
  command: "/usr/bin/shinken install {{ item }}"
  when: "'{{ item }}' not in shinken_inventory.stdout_lines"
  with_items:
    - webui
    - auth-cfg-password
    - sqlitedb

- name: Deploy webui and sqlite configuration
  template:
    dest: "/etc/shinken/modules/{{ item }}.cfg"
    src: "../templates/{{ item }}.cfg.j2"
  notify: restart shinken
  with_items:
    - webui
    - sqlitedb
